import { HDKey } from "@scure/bip32";
import { mnemonicToSeedSync, validateMnemonic } from "@scure/bip39";
import { wordlist } from "@scure/bip39/wordlists/english.js";
import { secp256k1 } from "@noble/curves/secp256k1.js";
import { keccak_256 } from "@noble/hashes/sha3.js";
export type EthereumResult=Readonly<{address:string;publicKey:string;privateKey:string}>;
export function inspectMnemonic(value:string){const normalized=value.normalize("NFKD").trim().toLowerCase().split(/\s+/u).filter(Boolean).join(" ");const wordCount=normalized?normalized.split(" ").length:0;if(![12,15,18,21,24].includes(wordCount))return{valid:false as const,message:"Нужно 12, 15, 18, 21 или 24 слова.",normalized,wordCount};if(!validateMnemonic(normalized,wordlist))return{valid:false as const,message:"Неверные слова или контрольная сумма BIP39.",normalized,wordCount};return{valid:true as const,normalized,wordCount};}
export function deriveEthereum(input:Readonly<{mnemonic:string;passphrase:string;path:string}>):EthereumResult{const v=inspectMnemonic(input.mnemonic);if(!v.valid)throw new Error(v.message);if(!input.path.startsWith("m/44'/60'/"))throw new Error("Ethereum-путь должен начинаться с m/44'/60'/.");const seed=mnemonicToSeedSync(v.normalized,input.passphrase.normalize("NFKD"));const root=HDKey.fromMasterSeed(seed);const child=root.derive(input.path);try{if(!child.privateKey)throw new Error("Приватный ключ не получен.");const pub=secp256k1.getPublicKey(child.privateKey,false);const raw=hex(keccak_256(pub.slice(1)).slice(-20));return{address:checksum(raw),publicKey:`0x${hex(pub)}`,privateKey:`0x${hex(child.privateKey)}`};}finally{seed.fill(0);root.wipePrivateData();child.wipePrivateData();}}
function checksum(raw:string){const hash=hex(keccak_256(new TextEncoder().encode(raw)));let out="";for(let i=0;i<raw.length;i++)out+=Number.parseInt(hash[i],16)>=8?raw[i].toUpperCase():raw[i];return`0x${out}`;}
function hex(v:Uint8Array){return Array.from(v,b=>b.toString(16).padStart(2,"0")).join("");}
